# Generated by Django 4.2.4 on 2023-08-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('edition', models.CharField(max_length=20)),
                ('publication_year', models.SmallIntegerField()),
                ('aurhors', models.ManyToManyField(to='core.author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
