# Generated by Django 4.2.4 on 2023-08-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='aurhors',
            new_name='authors',
        ),
    ]
