# Generated by Django 4.2.4 on 2023-08-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigIntegerField(default=75666746993640, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigIntegerField(default=123504860692690, editable=False, primary_key=True, serialize=False),
        ),
    ]
