name: Library - Fly.io deploy

on:
  workflow_run:
    workflows:
      - Integração contínua
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
    environment:
      name: production
      url: https://pguillen-library.fly.dev
 