name: runtests

on: push

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
      DJANGO_SETTINGS_MODULE: libraryapi.settings
    runs-on: ubuntu-latest

    steps:
      - name: Update
        run: sudo apt update

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configuração de Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: copy .env
        run: |
          cp .env-sample .env

      - name: Lint with flake8
        run: flake8 libraryapi/

      - name: Execute tests
        run: pytest libraryapi/
  